AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cloudformation Template for Kittens Carousel Static Website on EC2. 
  This template deploys Kittens Carousel Static website on 
  Amazon Linix 2 EC2 Instance with custom security group allowing 
  http connctions on port 80.Kittens Carousel Static Website is 
  downloaded from GitHub repository, then deployed on Apache Web Server.

Parameters: 

Metadata:

Mappings:

Conditions:

Resources:
  WebServerSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable HTTP for Apache Web Server and SSH for terminal
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: My first Security Group from cloudformation

  WebServerHost:
    Type: "AWS::EC2::Instance"
    Properties:
      
      ImageId: ami-0c94855ba95c71c99
      InstanceType: t2.micro
      KeyName: key
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::Stackname} Stack
      UserData: 
        Fn::Base64:
          !Sub |
            #! /bin/bash
            yum update -y
            yum install httpd -y
            cd /var/www/html/
            
      Volumes:
        - Volume
    
    
    VpcId: String



