AWSTemplateFormatVersion: 2010-09-09
Description: >
  CloudFormation Template for Roman Numerals Converter Application. This template creates
  Python Flask Web Application on Amazon Linux 2 (...................) EC2 Instance with
  custom security group allowing http connections on port 80.
  Roman Numerals Converter Application is downloaded from Github repository, then installed on Flask.
Parameters:
 Parameters:
  KeyPairName:
    Description: Enter the name of your Key Pair for SSH connections.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must one of the existing EC2 KeyPair
Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP for Flask Web Server
      SecurityGroupIngress:
        - IpProtocol: ...
          FromPort: ...
          ToPort: ....
          CidrIp: ....
        - IpProtocol: ....
          FromPort: ....
          ToPort: ....
          CidrIp: ......
  WebServerHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: .............
      InstanceType: ...........
      KeyName: !Ref .............
      SecurityGroupIds:
        - !Ref .....................
      Tags:                
        -                        
          Key: Name
          Value: !Sub ...........................  
      UserData:
        Fn::Base64: 
          !Sub |
            #! /bin/bash
            .......................
            .......................
            .......................
            wget -P templates https://raw.githubusercontent.com/...............................
            wget -P templates https://raw.githubusercontent.com/...............................
            wget https://raw.githubusercontent.com/......................................
Outputs:
  WebsiteURL:
    Value: !Sub 
      - ..................................................
      - ..................................................
    Description: .........................................